# Welcome to Jekyll!
#

# Site settings
title: LuxCyberChallenge 2018
description: Luxembourg Cyber Security Challenge 2018
owner: Securitymadein.lu
first_published: 2018 # if migrating another site, the year of your first publish
email:
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ecsc.lu" # the base hostname & protocol for your site
social:
twitter: https://twitter.com/VestaTechSpace
  #github: https://github.com/<username>
linkedin-square: https://www.linkedin.com/showcase/vestatech-luxembourg/
facebook-official: https://www.facebook.com/VestaTechLuxembourg
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed

deploy:
  - rsync -aze ssh --delete ./ mfa@c-3.lu:/var/www/ecsc.lu/www/

